# StudentLedger LR2 — статический адрес внутреннего сегмента, ВМ PROD.
# Файл предназначен для /etc/netplan/60-studentledger.yaml на studentledger-prod.
network:
  version: 2
  ethernets:
    slca-internal:
      match:
        macaddress: "08:00:27:51:a0:03"
      set-name: slca-internal
      dhcp4: false
      dhcp6: false
      addresses:
        - 192.168.56.13/24
