# StudentLedger LR2 — статический адрес внутреннего сегмента, ВМ STAGE.
# Файл предназначен для /etc/netplan/60-studentledger.yaml на studentledger-stage.
network:
  version: 2
  ethernets:
    slca-internal:
      match:
        macaddress: "08:00:27:51:a0:02"
      set-name: slca-internal
      dhcp4: false
      dhcp6: false
      addresses:
        - 192.168.56.12/24
